substitutions:
        name: esp32-bluetooth-proxy-1aae10
        friendly_name: Bluetooth Proxy Wemos
packages:
        esphome.bluetooth-proxy: github://esphome/firmware/bluetooth-proxy/esp32-generic.yaml@main
esphome:
        name: ${name}
        name_add_mac_suffix: false
        friendly_name: ${friendly_name}
api:
        encryption:
                key: !secret btprox_key


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password


esp32_ble_tracker:
        scan_parameters:
                interval: 1100ms
                window: 1100ms
        
bluetooth_proxy:
        active: true

external_components:
        - source: github://pr#5230
          components:
                  - esp_adf
          refresh: 0s

captive_portal:

